"""
kb_store.py - Layer 5
Thread-safe in-memory Knowledge Base with JSON persistence.
"""

import json
import threading
from config import KB_JSON_PATH

_kb: list[dict]   = []
_kb_lock          = threading.Lock()


# ── Write ──────────────────────────────────────────────────────────────────────

def add_entry(entry: dict) -> None:
    with _kb_lock:
        _kb.append(entry)
    _persist()


# ── Read ───────────────────────────────────────────────────────────────────────

def get_all() -> list[dict]:
    with _kb_lock:
        return list(_kb)


def get_recent(n: int = 10) -> list[dict]:
    with _kb_lock:
        return list(_kb[-n:])


def get_by_severity(level: str) -> list[dict]:
    with _kb_lock:
        return [e for e in _kb if e.get("severity", "").lower() == level.lower()]


def get_flagged(flag: str) -> list[dict]:
    """Return all entries containing a specific flag string."""
    with _kb_lock:
        return [e for e in _kb if flag in e.get("flags", [])]


def get_last_n_minutes(minutes: int) -> list[dict]:
    """
    Return KB entries whose window_id falls in the last N minutes worth of windows.
    At WINDOW_SIZE=30 rows (30 s), 1 minute = 2 windows.
    """
    from config import WINDOW_SIZE
    windows_per_minute = 60 // WINDOW_SIZE
    target_count = minutes * windows_per_minute
    with _kb_lock:
        return list(_kb[-target_count:]) if len(_kb) >= target_count else list(_kb)


def summary_stats() -> dict:
    with _kb_lock:
        data = list(_kb)
    if not data:
        return {}
    sevs = [e["severity"] for e in data]
    return {
        "total_windows":    len(data),
        "critical_count":   sevs.count("CRITICAL"),
        "warning_count":    sevs.count("Warning"),
        "normal_count":     sevs.count("Normal"),
        "info_count":       sevs.count("Info"),
        "first_window_time": data[0]["time_range"].split(" -> ")[0],
        "last_window_time":  data[-1]["time_range"].split(" -> ")[-1],
    }


# ── Fallback rule-based summary (used when LLM is unavailable) ─────────────────

def rule_based_summary(query: str = "") -> str:
    """
    Generate a plain-text answer from KB stats alone —
    used as LLM fallback when Ollama is unreachable or times out.
    """
    stats = summary_stats()
    if not stats:
        return ("The system is still collecting data — no windows have been "
                "processed yet. Please wait a few moments and try again.")

    all_flags: list[str] = []
    with _kb_lock:
        for e in _kb:
            all_flags.extend(e.get("flags", []))

    recent = get_recent(6)
    recent_sevs = [e["severity"] for e in recent]

    lines = []

    # Overall health
    critical = stats["critical_count"]
    warnings = stats["warning_count"]
    total    = stats["total_windows"]

    if critical > 0:
        lines.append(f"ALERT: {critical} critical event(s) recorded during this trip. "
                     "Immediate attention may be required.")
    if warnings > 0:
        lines.append(f"There have been {warnings} warning window(s) out of {total} "
                     f"analysed ({100*warnings//total}% of trip time).")
    else:
        lines.append(f"No warnings detected across {total} windows. Battery health looks good.")

    # Specific flag insights
    if "HIGH_TEMP" in all_flags or "CRITICAL_TEMP" in all_flags:
        count = all_flags.count("HIGH_TEMP") + all_flags.count("CRITICAL_TEMP")
        lines.append(f"Elevated temperature was flagged in {count} window(s) — "
                     "thermal stress has been a recurring factor.")
    if "HIGH_CURRENT" in all_flags:
        lines.append("High current draw was detected — aggressive acceleration phases occurred.")
    if "RAPID_SOC_DROP" in all_flags:
        lines.append("Rapid SoC depletion was observed — battery is draining faster than normal.")
    if "REGEN_BRAKING" in all_flags:
        lines.append("Regenerative braking detected — energy recovery is active.")
    if "LOW_SOC" in all_flags or "CRITICAL_SOC" in all_flags:
        lines.append("Battery charge level is low or has been critically low — plan a charging stop.")

    # Recent trend
    if recent_sevs:
        if recent_sevs[-1] == "CRITICAL":
            lines.append("The most recent window is showing a CRITICAL condition — take action now.")
        elif recent_sevs[-1] == "Warning":
            lines.append("The battery is currently in a warning state — conditions are deteriorating.")
        else:
            lines.append("Recent readings show the battery is currently stable.")

    lines.append("(Note: This response was generated by the rule engine — LLM was unavailable.)")
    return " ".join(lines)


# ── Persistence ────────────────────────────────────────────────────────────────

def _persist() -> None:
    try:
        import os
        os.makedirs(KB_JSON_PATH.rsplit("\\", 1)[0], exist_ok=True)
        with _kb_lock:
            snapshot = list(_kb)
        with open(KB_JSON_PATH, "w", encoding="utf-8") as f:
            json.dump(snapshot, f, indent=2, default=str)
    except Exception as e:
        pass   # non-critical; don't crash pipeline over disk issues


def load_from_disk() -> int:
    global _kb
    try:
        with open(KB_JSON_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        with _kb_lock:
            _kb = data
        return len(_kb)
    except FileNotFoundError:
        return 0
    except Exception:
        return 0
